### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by buntay** [germanrcuriel/conan-exiles-admin-map#3]
I am the server administrator. I have a question. Can I take your code for the list of players and place it on my site so that it will update itself? and how do i do that?
![inked _li](https://user-images.githubusercontent.com/47409343/52391704-ae189200-2aaf-11e9-9703-4f85c55fb67a.jpg)

**Comment by germanrcuriel** [comment]
Sorry for the late response. As it is now there's no way to export content as a widget 😢
